---
title: "In class 09/15"
author: "J Lacasa"
date: "2025-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R packages 

```{r}
library(tidyverse)
library(lme4)
```

# Data 
```{r}
library(agridat)
data("gomez.splitplot.subsample")
df <- gomez.splitplot.subsample
```

# ANOVA table
```{r}
t_spl <- data.frame(
  Source = c("Block", "Management", "Management(Block)", "Time",
             "MxT", "T(MxB)", "Error", "Total"),
  df = c("2", "7", 
         "14", 
         "3", "21",
         "48", "96", "191"))

knitr::kable(t_spl, caption = "ANOVA table for the fungicide-barley split-plot design. See also Table 24.9 from Milliken and Johnson as a helpful reference.")
```

# Model fitting

MLE
```{r}
m_MLE <- lmer(height ~ time*manage + (1|rep/manage/time), data = df, 
          REML = F)
```

REML
```{r}
m_REML <- lmer(height ~ time*manage + (1|rep/manage/time), data = df, 
          REML = T)
```

ANOVA
```{r}
m_anova <- aov(height ~ time*manage + Error(rep/manage/time), data = df)
```

Variance components with MLE
```{r}
VarCorr(m_MLE)
```

Variance components with REML
```{r}
VarCorr(m_REML)
```

Variance components with MoM
```{r}
#sigma^2_b 
sqrt(((2632.167/2) - (1324.295/14))/(2*4*8))

#sigma^2_wp 
sqrt(((1324.295/14) - (1653.080/48))/(2*4))

#sigma^2_sp 
sqrt(((1653.080/48) - (167.39/96))/2)

#sigma^2_e 
sqrt(167.39/96)
```



