---
title: "R Notebook"
output: html_document
---

```{r}
library(tidyverse)
library(ggpubr)
library(glmmTMB)
```

```{r}
url <- "https://raw.githubusercontent.com/stat870/fall2025/refs/heads/main/data/herbicide_study.csv"
d <- read.csv(url) |> 
  mutate(location = as.factor(location))
```

```{r}
d |> 
  ggplot(aes(plant_count))+
  geom_histogram(aes(group = herbicide, fill = herbicide), 
                 bins = 30, color = "black")+
  labs(fill = "Herbicide", 
       y = "Plant count")+
  theme_pubclean()+
  scico::scale_fill_scico_d(palette = "hawaii")
```


```{r}
m_pois <- glmmTMB(plant_count ~ herbicide + (1|location/herbicide),
        family = poisson(link = "log"),
        REML = T,
        data = d)

res <- DHARMa::simulateResiduals(m_pois)

DHARMa::testZeroInflation(res)
plot(res)
```


```{r}
m_zipois <- glmmTMB(plant_count ~ herbicide + (1|location/herbicide),
        family = poisson(link = "log"),
        ziformula = ~1,
        REML = T,
        data = d)

res <- DHARMa::simulateResiduals(m_zipois)

DHARMa::testZeroInflation(res)
plot(res)
```


```{r}
m_zipois2 <- glmmTMB(plant_count ~ herbicide + (1|location),
        family = nbinom1(link = "log"),
        ziformula = ~1 + herbicide,
        REML = T,
        data = d)

res <- DHARMa::simulateResiduals(m_zipois2)

DHARMa::testZeroInflation(res)
plot(res)

summary(m_zipois2)
emmeans::emmeans(m_zipois2, ~herbicide)
```


```{r}
m_zinb <- glmmTMB(plant_count ~ herbicide + (1|location/herbicide),
        family = nbinom1(link = "log"),
        ziformula = ~1,
        REML = T,
        data = d)

res <- DHARMa::simulateResiduals(m_zinb)

DHARMa::testZeroInflation(res)
plot(res)
summary(m_zinb)
```



